name: job_timer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #modular
  flutter_modular: ^5.0.2
  modular_bloc_bind: ^1.0.1
  asuka: ^2.0.0+1 #mensagens and alert

  #general
  validatorless: ^1.2.1 #validators
  fl_chart: ^0.51.0 #grafics

  #login with google
  google_sign_in: ^5.3.2
  #firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19

  #bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  #No sql
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  path_provider: 2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  isar_generator: 2.5.0
  build_runner: ^2.1.11

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
    - family: IconsAPP
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
